src/models/Idea.js
src/routes/api/idea.js

allow exclude and include with AND operators on the IDEA resource route
?exclude[theme]=Green
this also works:
?exclude[theme][]=Green&exclude[theme][]=blue
Also fixed issue, making include filters with AND operator instead or

allow exclude and include with AND operators

---

src/middleware/site.js
src/routes/api/user.js

Allow for deleting a user. Set ideas, votes and arguments to deletedAt when deleting a user and delete the oauth User if there are no other sites this user is active on.

Deleting users via API including it's resources

---

CHANGELOG.md
src/util/sanitize.js

This prevents the `sanitize` function transforming null into the string 'null'. 
Fixes #103

Add decorator around the sanitize util and replace its usage

---

src/services/oauth-api.js

User that use an email that contain special characters (like `+`) could not signup because the email was not correctly escaped inside url.
This created a bug when a user already existed in the auth api but was not found when requesting that user from the oauth api. The openstad-api would then try to create a new user which would fail because of a duplicate entry.

fix(oauth): encode email in path

---

.eslintrc.json
.github/workflows/lint.yml
package-lock.json
package.json
prettier.config.js

Added prettier and ESlint commands to validate and fix code styling.
- Add prettier script to fix code styling
- Add lint script to validate code with ESlint
- Add github workflow action to run ESlint on every push
Please check the config of Prettier and ESlint. I'll fix all the files at once in another branch/commit if you agree with these settings. 
**Notes:**
- Would be nice if we use the same approach and settings for every Openstad repository. 
- As an extra tool on top, we can use SonarCloud.

Add Prettier and ESlint

---

Dockerfile
package-lock.json

Due to an update in the default repositories in the underlying `alpine` image, `python` no longer refers to the correct version for our build. Changing it to `python3` will allow the build to complete succesfully. See https://stackoverflow.com/questions/62169568/docker-alpine-linux-python-missing
Ideally we'd update to version 18 straight away, but that seems a bit less straightforward. Updating to version 16 (which has security support until september 11th 2023) buys us time to come up with a good strategy to upgrade further.

Update node to 16.16 w/ underlying dependencies

---

src/cron/close_ideas.js

No sites where found where the config key `ideas.automaticallyUpdateStatus.isActive` was set to true because the compared value was a boolean not a string.
Related to: https://trello.com/c/lQBlDsaO/57-automatisch-sluiten-van-ideas-werkt-niet

fix: change query to non boolean comparison

---

src/models/Idea.js

When a user uses special chars like & or © these chars get sanitized by the sanitize-html package. Because of this the length of the string changes which fails the validation.
For example: 
```
Een Bokszakken/Fitness-Systeem op het Zoutkeetsplein aanleggen, t.b.v. Social-Sport&SharIng-Programma’s voor verschillende buurtdoelgroepen.
```
Becomes:
```
Een Bokszakken/Fitness-Systeem op het Zoutkeetsplein aanleggen, t.b.v. Social-Sport&amp;SharIng-Programma’s voor verschillende buurtdoelgroepen.
```
This fix parses html entities before validating length.
Related to this issue: https://trello.com/c/3k5yizBI/63-planformulier-vindt-niet-leuk

fix: check length of unsanitized string

---

migrations/033-add-contstraint-to-users-to-avoid-duplicate-user-for-single-site.js

Some users have a double entry in the users table with the same site id. Because of this users can't login and get shown the message:
> Meerdere users gevonden
By adding this constraint it should not be possible to have duplicate entries.
To check if you database has duplicate entries you can use this query:
```sql
SELECT u.email,
u.siteId,
u.id,
u.externalUserId,
u.createdAt,
u.updatedAt,
u.deletedAt
FROM users u
JOIN (
SELECT email,
siteId
FROM users
GROUP BY email,
siteId
HAVING count(email) > 1
AND count(siteId) > 1
) d ON u.email = d.email
AND u.siteId = d.siteId;
```

Add constraint to users table to avoid duplicate users for same site

---

src/models/ChoicesGuide.js
src/models/ChoicesGuideChoice.js
src/models/ChoicesGuideQuestion.js
src/models/ChoicesGuideQuestionGroup.js
src/models/IdeaTag.js
src/models/NewsletterSignup.js
src/models/Tag.js

Admin functionality on a website (/admin, a.k.a. react-admin) works incorrectly for moderators and editors. This update fixes that. See also https://github.com/openstad/openstad-frontend/pull/355
Let's consider this a bug fix
Documentation will be updated after this PR is merged
Only locally

Update access rights

---

CHANGELOG.md
README.md
src/db.js

Currently it's not possible to connect to a MySQL server through SSL. This PR adds a `MYSQL_CA_CERT` environment variable which allows us to add a CA (Certificate Authority) certificate. When this certificate is provided, it is added to the MySQL connection options, and invalid SSL handshakes / certificates are rejected.
Related PRs have been made in the auth, image & kubernetes repositories: 
https://github.com/openstad/openstad-oauth2-server/pull/113
https://github.com/openstad/openstad-image-server/pull/35
https://github.com/openstad/openstad-kubernetes/pull/78
New feature through an environment variable. Keeps backwards compatibility.
See README.md
Locally

Add `MYSQL_CA_CERT` for MySQL SSL connection

---

src/models/Action.js

Action run searches for the last run and errors if that does not exist.
Not anymore.

Fix an error in the running of actions on an empty database

---

src/models/Site.js

The config value projectHasEnded was moved from the root of the config to the project tree. Backwards compatibility wasn't working properly.

Fix the backwards compatibility for site.config.projectHasEnded

---

migrations/040-locks-type-unique.js
src/lib/use-lock.js

The locking mechanism as is does not work as intended. Sequelize transactions do not lock the table, and using seqeulize to create table locks seems only possible with raw queries.
A blunt but effective alternative is used here: make the type field in the locks table unique, and prevent multiple instances by (mis)using mysql's capabilities.
Fixes #255 
Let's call this a bug fix

Make locks type unique

---

src/routes/api/vote.js

There is a discrepancy between the API and the managagement-panel/react admin: can moderators view votes.
This change fixes that: only admins can view votes.

Votes should only be viewable by admins

---

src/routes/api/vote.js

Recently the show-votes route has been updated: only admins can now see votes. This has been done incorrectly:
The function `userhasModeratorRights(user)` was sometimes used as `userhasModeratorRights(role);`. 
This change fixes that.

Use the correct paramater

---

src/models/ChoicesGuide.js

**Issue**: result form and login settings are used when the result should be automatically sent
**Fix**: on save unset config values when the form is not shown.

parse choices-guide config before saving

---

src/models/Site.js

When a site is deleted it will leave existing users behind.
These users should have been anonymized. They were not, and will not be found in existing checks.
The easiest fix, and maybe most consistent, is to disabling the deleting of sites that have not been anonymized. That is what is fix does.
By requiring to use the existing anonymize functionality we prevent future mismatches between this and other parts of the code.

Add check on existing users bofore deleting a site

---

migrations/041-add-tag-column-type.js
src/models/Tag.js

Added a migration to add type column and exposed it

---

src/models/Site.js
src/routes/api/site.js

Anonimizing the users of a site on the background. 
I have taken an example of the class auth/middleware/code.js

Rework classes to anonymize users in the background
