src/routes/api/vote.js
Enable sorting by query param in get votes route
=> Export votes

migrations/008-choices-guide-result-extradata.js, npm-debug.log, package-lock.json, src/models/ChoicesGuideResult.js, src/routes/api/choicesguide.js
Related ticket: https://trello.com/c/9jN8ge8N
=> Add extraData to ChoicesGuideResult

migrations/009-user-siteId.js, src/auth/roles/default/default-unknown.js, src/auth/roles/default/editor.js, src/auth/roles/default/index.js, src/auth/roles/default/member.js, src/auth/roles/default/moderator.js, src/db.js, src/middleware/brute-force.js, src/models/IdeaTag.js, src/models/User.js, src/routes/api/idea.js, src/routes/api/index.js, src/routes/api/tag.js, src/routes/api/user.js, src/routes/oauth/oauth.js
user CRUD route in api.
Allows for ability to manage users for moderators.
Allows for users to edit their own data.
https://trello.com/c/BI7JCBbq/123-user-crud-route-in-openstadapi
=> User CRUD route in openstadapi

config/default.json, doc/index.md, doc/stats.md, src/routes/stats/idea.js, src/routes/stats/index.js, src/routes/stats/vote.js
Add stats endpoints
Related ticket: https://trello.com/c/A3W4tVWn
=> Add stats endpoints

.dockerignore, Dockerfile
Transfering dockerfiles back to the projects
=> docker files from openstad-kubernetes

src/models/Site.js, src/routes/api/vote.js
Hotfix on master is easier merged as a new branch
=> Add merge to voting types

src/routes/api/idea.js
make-sure-location-is-not-empty-object
=> make-sure-location-is-not-empty-object

package-lock.json, package.json, src/services/checkHostStatus.js
Add IP check to cron site host status
=> Add IP check to cron site host status

src/routes/oauth/oauth.js
Related ticket: https://trello.com/c/IRE4Cy6W
=> Add phonenumber as criterium for member role

src/models/Idea.js, src/routes/api/idea.js
Make the idea requests much faster
=> Remove Site form default Idea scope

src/routes/api/vote.js
Related ticket: https://trello.com/c/Kup5xj7g
=> Add min/max number of plans to budget voting

src/models/Idea.js, src/routes/api/user.js
Create user via the openstad API.
1. Check if user exists in oAuth
2. If yes move one, otherwisre create
3. Check if user exists in openstad API, if yes throw error
4. Otherwise create the new user in openstad API
=> Create user via the openstad API

src/routes/api/user-activity.js
=> add sites to user activity

src/routes/api/argument.js, src/routes/api/idea.js, src/routes/api/user.js
Wat extra's om de Stem Van websites te kunnen overzetten.
=> A  some extra functionality to simplify imports

CHANGELOG.md, src/routes/stats/choicesguide.js, src/routes/stats/index.js
Add choices guide stats endpoint.
=> Choices guide result counter stats

CHANGELOG.md, src/models/Idea.js, src/models/Submission.js, src/routes/api/submission.js, src/util/getSequelizeConditionsForFilters.js
This allows the react-admin to list and view the submissions, and generate a CSV export.
Related ticket: https://trello.com/c/MHQ88xsW/81-inzendingen-resource-form-submission-beschikbaar-maken-voor-export
=> Make submissions listable and viewable

.github/ISSUE_TEMPLATE/bugs.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Add github issue templates for bugs an features.
Add a link to Tthe OpenStad community page
New feature
N/A
N/A
=> Add issue templates

src/models/Idea.js
Ideas should not be editable after the first like or argument has been added. This did not work as it should.
=> Fix arg and like count when editing ideas

src/cron/send_enddate_notifications.js
The selection of sites that need to be notified about an upcoming end date was was wrong and is fixed here.
=> Fix selecting of sites to notify

src/middleware/site.js, src/routes/api/index.js, src/routes/api/lock.js
A new system of locks was introduced, to make sure that automated API processes will not run more than once.
This change adds the management of locks.
This is a new feature
=> Add locks management

src/db.js
=> Trim MYSQL_CA_CERT

src/services/checkHostStatus.js
Kubernetes API gives 404 error because of deprecated api
bug fix, breaking depending on kubernetes cluster version
master
=> fix: upgrade to non beta apiVersions

src/models/Site.js
=> Change site listable to moderator

src/routes/api/idea.js
An alt for https://github.com/openstad/openstad-api/pull/275
=> Add tags parsing to put/post ideas

src/routes/api/user.js
Creating a user through react-admin crashes with an error 'user.lastLogin cannot be null'
This patch sets the lastlogin date to 'now' wheen creating a user.
It also adds zipcode to accepted fields.
=> Add lastlogin to create user

README.md, email/concept_ideas_created.njk, email/concept_ideas_edited.njk, migrations/041-add-tag-column-type.js, package-lock.json, package.json, src/lib/defaultSiteConfig.js, src/lib/mail-config.js, src/lib/mail.js, src/models/Idea.js, src/models/Site.js, src/models/Tag.js, src/routes/api/idea.js, src/routes/api/site.js, src/routes/api/tag.js, src/routes/api/user.js
=> Nieuwe release van master

src/models/Tag.js
=> bypass sanitazion if the give type is falsy and set null

src/routes/api/article.js
=> Added auth.useReqUser to route delete on article

src/middleware/publish-concept.js
=> Fixes the sudden saving to submitted when removing budgetdocuments

src/models/Idea.js
=> Added safety check before trimming

src/models/Idea.js
=> Only prettify changes and trim safety check

README.md
=> chore(readme): add archive notice
